#[=======================================================================[.rst:
cppbinder

The following command is defined for use with RosettaCommons/binder and pybind11:

.. command:: cppbinder_add_target

	.. versionadded:: 3.5

	Generate bindings with binder for given HEADERS and compile_commands.json.
	It starts a seperate cmake project during building to be able to read the current compile_commands.json.

	.. code-block:: cmake

    cppbinder_add_target(<name>
		[BINARYFOLDER <directory>]
		ROOTMODULE <modulename>
		[OUTPUTFOLDER <directory>]
		CONFIGFILE <file>
		PROJECTLIB <file|target>
		[PROJECTINCLUDES <file>...]
		[PROJECTEXTRASOURCES <file>...]
		HEADERS	<file>...			
	)

	``BINARYFOLDER``
		Binary folder to use for subproject, defaults to ${CMAKE_CURRENT_BINARY_PATH}/bindings-bld

	``ROOTMODULE``
		The name of the rootmodule, same as binder --root-module ${ROOTMODULE}

	``OUTPUTFOLDER``
		Specify a directory where the compiled bindings file will be placed.
		Default is ${CMAKE_CURRENT_BINARY_DIR}/${name}

	``CONFIGFILE``
		The configfile to use, same as binder --config ${CONFIGFILE}

	``PROJECTLIB``
		The library file|target to link to the generated binary, the target will be dependend on that file|target

	``PROJECTINCLUDES``
		List of includes to add the generated pybind target, should be at least the ones used for ``PROJECTLIB``
	
	``PROJECTEXTRASOURCES``
		Additional source files to be handed over to the pybind target in addition to the ones generated by binder	

	``HEADERS``
		List of headers from which the includes will be extracted and used to generate the bindings.
		To compare the resulted inputs check ${BINARYFOLDER}/includes_for_bindings.h
	

#]=======================================================================]

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# cppbinder_add_target(<name>
# 		[BINARYFOLDER <directory>]
# 		ROOTMODULE <modulename>
# 		[OUTPUTFOLDER <directory>]
# 		CONFIGFILE <file>
# 		PROJECTLIB <file|target>
# 		[PROJECTINCLUDES <file>...]
# 		[PROJECTEXTRASOURCES <file>...]
# 		HEADERS	<file>...			
# 	)
function(cppbinder_add_target name)
	set(options "")
	set(oneValueArgs 
		BINARYFOLDER
		ROOTMODULE
		OUTPUTFOLDER
		CONFIGFILE
		PROJECTLIB
	)
	set(multiValueArgs 
		HEADERS
		PROJECTINCLUDES
		PROJECTEXTRASOURCES
	)
	cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
	
	if(NOT DEFINED ARG_HEADERS)
		message(FATAL_ERROR "cppbinder_add_library: Missing HEADERS argument")
	endif()

	if(NOT DEFINED  ARG_ROOTMODULE)
		message(FATAL_ERROR "cppbinder_add_library: Missing ROOTMODULE argument")
	endif()

	if(NOT DEFINED  ARG_PROJECTLIB)
		message(FATAL_ERROR "cppbinder_add_library: Missing PROJECTLIB argument")
	endif()

	if(NOT DEFINED  ARG_CONFIGFILE)
		message(FATAL_ERROR "cppbinder_add_library: Missing CONFIGFILE argument")
	endif()

	if(NOT DEFINED  ARG_BINARYFOLDER)
		set(ARG_BINARYFOLDER "${CMAKE_CURRENT_BINARY_DIR}/bindings-bld")
	endif()

	if(NOT DEFINED  ARG_OUTPUTFOLDER)
		set(ARG_OUTPUTFOLDER "${CMAKE_CURRENT_BINARY_DIR}/${name}")
	endif()

	add_custom_target(${name}
		COMMAND cmake -G ${CMAKE_GENERATOR}
			-S "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/cppbinder"
			-B "${ARG_BINARYFOLDER}"
			-D headers_to_bind_file="${ARG_HEADERS}"
			-D root_module_name="${ARG_ROOTMODULE}"
			-D project_lib_file="${ARG_PROJECTLIB}"
			-D project_includes="${ARG_PROJECTINCLUDES}"
			-D project_extra_sources="${ARG_PROJECTEXTRASOURCES}"
			-D binder_config_file="${ARG_CONFIGFILE}"
			-D output_dir="${ARG_OUTPUTFOLDER}"
			-D compile_commands_file="${CMAKE_BINARY_DIR}/compile_commands.json"
			-D Python_EXECUTABLE="${Python_EXECUTABLE}"
			-D Python_INCLUDE_DIRS="${Python_INCLUDE_DIRS}"
			-D Python_NumPy_INCLUDE_DIRS="${Python_NumPy_INCLUDE_DIRS}"
		USES_TERMINAL
		DEPENDS ${ARG_PROJECTLIB}
		SOURCES ${ARG_HEADERS}
	)

	add_custom_target(${name}_build ALL
		COMMAND cmake --build ${CMAKE_CURRENT_BINARY_DIR}/bindings-bld
		USES_TERMINAL
		DEPENDS ${name}
	)
	
	
endfunction()